/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconAccountGroup: typeof import('./src/components/icons/iconAccountGroup.vue')['default']
    IconCake: typeof import('./src/components/icons/IconCake.vue')['default']
    IconCalendar: typeof import('./src/components/icons/IconCalendar.vue')['default']
    IconCash: typeof import('./src/components/icons/iconCash.vue')['default']
    IconCity: typeof import('./src/components/icons/IconCity.vue')['default']
    IconEmail: typeof import('./src/components/icons/IconEmail.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconPhone: typeof import('./src/components/icons/iconPhone.vue')['default']
    IconPost: typeof import('./src/components/icons/IconPost.vue')['default']
    IconSchool: typeof import('./src/components/icons/IconSchool.vue')['default']
    IconTencent: typeof import('./src/components/icons/IconTencent.vue')['default']
    IconWechat: typeof import('./src/components/icons/iconWechat.vue')['default']
    ResumeAppBar: typeof import('./src/components/ResumeAppBar.vue')['default']
    ResumeBlank: typeof import('./src/components/ResumeBlank.vue')['default']
    ResumeBlock: typeof import('./src/components/ResumeBlock.vue')['default']
    ResumeBlockCompactItem: typeof import('./src/components/ResumeBlockCompactItem.vue')['default']
    ResumeBlockItem: typeof import('./src/components/ResumeBlockItem.vue')['default']
    ResumeFill: typeof import('./src/components/ResumeFill.vue')['default']
    ResumeProfile: typeof import('./src/components/ResumeProfile.vue')['default']
    ResumeSkills: typeof import('./src/components/ResumeSkills.vue')['default']
    ResumeTimeline: typeof import('./src/components/ResumeTimeline.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarStep: typeof import('@varlet/ui')['_StepComponent']
    VarSteps: typeof import('@varlet/ui')['_StepsComponent']
  }
}
